global using System.Threading;
global using System.Threading.Tasks;
global using GameServer.Domain.Common;
global using System.Net.WebSockets;
global using System.Text.Json;
global using GameServer.Application.Common;
global using GameServer.Application.Common.Interfaces;
global using GameServer.Application.Services;
global using Microsoft.Extensions.DependencyInjection;