global using System;
global using System.Net.WebSockets;
global using System.Text;
global using System.Text.Json;
global using System.Threading;
global using System.Threading.Tasks;
global using GameServer.ConsoleClient.Model;
global using System.Text.Json.Serialization;
global using GameServer.ConsoleClient.Model.Request;
